# -------------------------------------------------
# 基本設定
# -------------------------------------------------

# prefixキーをC-tに変更する
set -g prefix C-t

# デフォルトでprefix がC-b になっているので、そのキーバインドを解除する
unbind C-b

# 256色サポート
set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"

# エスケープキーの遅延を解消（Vim向け）
set -sg escape-time 0

# ウィンドウとペインのインデックスを1から開始
set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on

# スクロールバックバッファを拡張
set -g history-limit 50000

# neovimのautoread対応
set -g focus-events on

# Prefix key が押されているかどうかを表示する
# https://qiita.com/dtan4/items/363e92525e7c5a16f3fc
set-option -g status-left '#[fg=cyan,bg=#303030]#{?client_prefix,#[reverse],} tmux #[default]'

# -------------------------------------------------
# ペイン操作
# -------------------------------------------------

# | でペインを縦に分割する
bind | split-window -h

# - でペインを横に分割する
bind - split-window -v

# ウィンドウの一覧を表示します．
bind w choose-tree -Zw

# -------------------------------------------------
# マウス操作
# -------------------------------------------------

#マウス操作を有効にする
set-option -g mouse on

# マウススクロールを有効化
bind-key -T edit-mode-vi WheelUpPane send-keys -X scroll-up
bind-key -T edit-mode-vi WheelDownPane send-keys -X scroll-down

# ダブルクリックでタイルレイアウトに変更
bind -n DoubleClick1Pane select-layout tiled

# -------------------------------------------------
# クリップボード
# -------------------------------------------------
set -s copy-command 'pbcopy'

# -------------------------------------------------
# キーバインド
# -------------------------------------------------

# Vimのキーバインドでペインを移動する
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
bind -r C-h select-window -t :-
bind -r C-l select-window -t :+

# Vimのキーバインドでペインをリサイズする
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5
